name: Publish Release

on:
  push:
    branches: [ master, kotlin-1.4 ]
    tags: 
      - "*"

jobs:
  macos-build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish artifacts
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        run: ./gradlew uploadArchives --no-daemon --no-parallel

  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish artifacts
      env:
        SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
        SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}   
      run: ./gradlew publishMingwPublicationToMavenRepository --no-daemon --no-parallel
